### PR TITLE
Upgrade to AprilTag 3, fix installation, and performance improvements

### LINKED ISSUE #20: Extremely High CPU Usage
A key advantage of Apriltags 2 over the original is supposedly the substantial savings in CPU. However i'm observing approximately 4x-5x more CPU usage by apriltags2 then by a previous implementation of the original apriltags algorithms (ported to C++) here: https://github.com/swatbotics/apriltags-cpp

### LINKED ISSUE #45: Fork/rename package to apriltag_ros to align with upstream Apriltag library
Continuing the discussion from [here](https://github.com/dmalyuta/apriltags2_ros/pull/43#issuecomment-479955663). With the release of Apriltag 3, should this `apriltags2_ros` package/repo be forked or renamed? 

The `2` suffix will become confusing if @wxmerkt's [update to Apriltag 3](https://github.com/dmalyuta/apriltags2_ros/pull/43) is merged.  

**Naming:**
- There's a mixture of repos called `apriltag` and `apriltags`, both with and without the plural
- The package in the upstream Apriltag 3 repo https://github.com/AprilRobotics/apriltags is consistently named `apriltag`  in `CMakeLists.txt` and `package.xml`, and `libapriltag` in the `Makefile`. 
- For consistency, I'd suggest this repo/package is forked/renamed to `apriltag_ros`?
- Once Apriltag is added to the ROS build farm [as discussed here](https://github.com/AprilRobotics/apriltags/issues/16), this will create the packages `apriltag` and `apriltag_ros`, which seems consistent.  

**Fork vs. rename?** 
 - How many people are building against the ROS package `apriltags2_ros` and this repo URL? Renaming will break things. 
- Since Apriltag 3 is out and Apriltag 2 is no longer being developed, perhaps this package should archived at version 2 and forked? 
- Can I propose forking this repo into `apriltag_ros` and merging @wxmerkt's [update to Apriltag 3](https://github.com/dmalyuta/apriltags2_ros/pull/43) into it instead?

@dmalyuta I'd be happy to do this, but will look for your guidance first!

**ROS Community:**
Before forking, we should probably figure how it fits with the broader community. A quick google turned up:
 - http://wiki.ros.org/apriltags2_ros points to this repo
 - http://wiki.ros.org/apriltags_ros  hasn't been updated since Indigo
 - https://github.com/XinkeAE/AprilTag_ROS has a single commit three years ago
 - https://github.com/anqixu/apriltag/tree/master/apriltag_ros untouched for five years
 - https://github.com/versatran01/apriltag has a couple of older Apriltag implementations

@dmalyuta how did you create the ROS wiki page?  If this repo is forked to `apriltag_ros`, can we create http://wiki.ros.org/apriltag_ros, and add redirect notices on the other wiki pages?

### PR DESCRIPTION
**Pull request by wxmerkt**
This is quite a big pull request and incorporates many other currently open pull requests. I hope to address both installation and performance issues with this one. 

- Upgrades to AprilTags 3, and in specific a thin CMake overlay of the now-officially-on-GitHub version. This replaces the apriltags2 catkin wrapper which was a fork and not fully working (installation...). AprilTags 3 should be faster by itself.
- As part of this, some tag families and options are gone (refine_pose, black_border, refine_decode)
- Renamed the libraries to include the project name as prefix. This avoids clashes with other `common` libraries.
- Removed the forced compilation in Debug. I think that is the source of performance issues that many people have highlighted and that can easily trip people up who just clone the repository.

Before I merge this, I'd like to get feedback from users and stakeholders that this works for their use cases and that it indeed fixes their issues.

In particular I think this PR will resolve:

- Resolves #22
- Resolves #32 (by incorporating and expanding on it - note: the libraries have now also been renamed to include the project name as prefix)
- Resolves #37 (by incorporating and expanding on it)
- Resolves #42 (by incorporating and expanding on it)
- Possibly resolves #20 and #35 (performance issues)
- Resolves #45 by renaming

### CODE REVIEW

**Comment by paulbovbel** [comment]
Looking forward to trying this!

Does the ROS buildfarm still have trouble with submodules? Consider using a cmake external project (https://github.com/locusrobotics/apriltag2)

**Comment by wxmerkt** [comment]
Thank you @paulbovbel! My plan is to switch over to CMake external project soon, add CI, and then release to the buildfarm.

**Comment by paulbovbel** [comment]
Nice. That way you should be able to use the upstream source (https://github.com/AprilRobotics/apriltags) without any kind of vendoring like in (https://github.com/christianrauch/apriltag2).

There's actually another approach via bloom (http://wiki.ros.org/bloom/Tutorials/ReleaseThirdParty), which I've used before to bloom vrpn (https://github.com/ros-drivers-gbp/vrpn-release). Let me know if you want a hand with that.

**Comment by wxmerkt** [comment]
@paulbovbel Thank you for the offer - very happy if you could assist with the release as a third-party library after @davelkan's 36h9 PR has been merged upstream.

**Comment by rgreid** [comment]
The CMake scripts and package.xml have been merged to the upstream source https://github.com/AprilRobotics/apriltags, which should make things easier. Seems to build fine. 

Should we encourage upstream to fix the mismatch between the repo name  `apriltags` and package name `apriltag`?

@dmalyuta Big picture question: given the upgrade to Apriltag 3, this repo/package name is outdated/confusing. Should we rename this repo to `apriltags_ros` _before_ pushing it to the ROS buildfarm?  Seems the right time to do it, while it's the least disruptive (github provides [redirects](https://help.github.com/en/articles/renaming-a-repository)).

**Comment by dmalyuta** [comment]
@rgreid I'm fine with changing the repo name to the more general version. Should it be named ``apriltags_ros`` or ``apriltag_ros``?

**Comment by rgreid** [comment]
> @rgreid I'm fine with changing the repo name to the more general version. Should it be named `apriltags_ros` or `apriltag_ros`?

I've branched this discussion to https://github.com/dmalyuta/apriltags2_ros/issues/45

**Comment by wxmerkt** [comment]
I've now updated the package to use the [apriltag library](https://github.com/AprilRobotics/apriltag) directly (just clone it into the same workspace until it's released) and renamed it to `apriltag_ros` (resolves #45). I am planning to tag this as version 2.0.0 once merged (with 1.0.0 being the last version using the current master). 

Can you please test it and give feedback whether that's good to go? @dmalyuta @rgreid  @mkrogius. Thank you very much :)

**Comment by rgreid** [comment]
Suggestion: Can we tag master from a month ago with `apriltags2_ros` and after the package rename to version `2.0.0`.  And once your Apriltag 3 branch has been merged `3.0.0`?  I.e. track the upstream version numbers (Sorry if I have misunderstood, can't browse the commits atm).

**Comment by wxmerkt** [comment]
Thanks for volunteering to test this @rgreid. The current master (`apriltags2_ros`) is already tagged as 1.0.0. I am intending to tag it as 2.0.0 after this has been merged (as `apriltag_ros`).

**Comment by wxmerkt** [comment]
Do you have any feedback on this PR @rgreid from testing? :-) If not, let's try to bloom-release the library and the wrapper this weekend.

**Comment by rgreid** [comment]
@wxmerkt I've had a colleague test the PR, however I'd like to test it myself in the next day or two (integrating into a much larger build system). Thanks

**Comment by rgreid** [comment]
LGTM! Builds and runs fine. I wonder if bloom ignores Git submodules? If so, then perhaps we should either 1) add the upstream `apriltag` repo as a submodule here or 2) add something in README.md about the `apriltag` prerequisite?

**Comment by wxmerkt** [comment]
Thank you very much for testing!

>  I wonder if bloom ignores Git submodules? If so, then perhaps we should either 1) add the upstream apriltag repo as a submodule here or 2) add something in README.md about the apriltag prerequisite?

I removed the submodule on purpose - there is a note in the new README that it depends on the upstream AprilTag library, but perhaps it's too subtle at the moment and should be made more clear. I'll do this post-merge.

**Pull request merged**
