### PR TITLE
Added service to start/stop continuous detection

### PR DESCRIPTION
**Pull request by adam-pensa**
Also added `autostart` parameter to continuous detection node to control stop/start behavior

### CODE REVIEW

**Comment by rgreid** [comment]
Thanks for your contribution. In your code you are shutting down the subscribers and publishers when the `stop` service is called. How is this any different to simply starting/stopping the node?

**Comment by adam-pensa** [comment]
The idea is to avoid the overhead of setting up a new process, ROS node, and TagDetector every time the user wants to start detecting again.

In addition, there is no clean way to kill a node from another node without resorting to system calls or an non-standard roslaunch setup.

**Comment by chadrockey** [comment]
@rgreid @adam-pensa The go-to way to do this in ROS is usually called "lazy subscriptions", that is, if no one is subscribed to your output topics, you unsubscribe from your input topics and you do no work.  ROS provides callback arguments that can be used to enable this functionality.

Topic tools relay is one of the simpler examples of this:
https://github.com/ros/ros_comm/blob/noetic-devel/tools/topic_tools/src/relay.cpp#L70

I might have some development time in the near future.  If I made a PR that accomplished this: (add a parameter, no subscribers to tag_detections, and no subscribers to tag_detections_image -> then unsubscribe from image_rect and camera info); would either of you like to see this functionality implemented this way?

**Comment by wxmerkt** [comment]
Hi @chadrockey,
Thank you very much for the references - I made a first version (without unsubscribing from topics due to the `publish_tf` option) in #80 - would love to hear your thoughts / feedback!

**Comment by wxmerkt** [comment]
#80 added lazy processing if there are no downstream users. Closing this explicit service to start / stop based on inactivity. May reconsider in the future if there is a case where the lazy processing does not suffice

**Pull request closed without merging**
