### PR TITLE
adding 36h9

### PR DESCRIPTION
**Pull request by davelkan-zz**
Adding the 36h9 tag family

### CODE REVIEW

**Comment by davelkan** [comment]
@dmalyuta

**Comment by wxmerkt** [comment]
We are about to upgrade to AprilTag 3 which does not ship with the 36h9 family - is this still of interest?

**Comment by davelkan** [comment]
Yes I would still like access to this tag family

**Comment by wxmerkt** [comment]
Would you consider trying to upstream it to https://github.com/AprilRobotics/apriltags/?

**Comment by davelkan** [comment]
kk

**Comment by davelkan** [comment]
https://github.com/AprilRobotics/apriltags/pull/12

**Comment by davelkan** [comment]
@wxmerkt thoughts on including 36h9? upstream said no

**Comment by wxmerkt** [comment]
I saw the upstream comment. We are about to remove the forked code and build on the officially released apriltag (once https://github.com/AprilRobotics/apriltags/pull/11 is merged and released via the ROS buildfarm as debians) - happy to integrate 36h9 if it can be done in a build step as part of the ROS module rather than the library?

**Comment by paulbovbel** [comment]
Thanks @wxmerkt, looks like that's a valid option.

**Comment by wxmerkt** [comment]
Hi @davelkan-zz,
If this is still of interest and you can re-base it on / make it work with the current master, happy to include it

**Comment by wxmerkt** [comment]
Closing as inactive. Happy to reconsider once made compatible with the latest master branch

**Pull request closed without merging**
