### PR TITLE
Add guard before destroy method in TagDetector destructor

### LINKED ISSUE #125: Initialize detections_ with empty struct
Maybe a special case of usage here, but

Running the node and not providing any input messages gives the following error when closing the node

```
^C[apriltag_ros_continuous_node-2] killing on exit
apriltag_ros_continuous_node: /tmp/binarydeb/ros-noetic-apriltag-3.2.0/common/zarray.h:132: zarray_size: Assertion `za != NULL' failed.
```

This is because in the [constructor](https://github.com/AprilRobotics/apriltag_ros/blob/master/apriltag_ros/src/common_functions.cpp#L157) of the TagDetector 

```
   detections_ = NULL;
```

The [desctructor](https://github.com/AprilRobotics/apriltag_ros/blob/master/apriltag_ros/src/common_functions.cpp#L166) wants to destroy `detections_` with 

```
  apriltag_detections_destroy(detections_);
```

But `zarray_size` [asserts](https://github.com/AprilRobotics/apriltag/blob/master/common/zarray.h#L132) if the pointer points to NULL.

Is it possible to initialize `detections_` with something else than `NULL` ?

### PR DESCRIPTION
**Pull request by maximilianwulf**
Fixes #125 

Was tested on our setup.

### CODE REVIEW

**Review by wxmerkt — APPROVED** [review]
Great, thank you for the fix!

**Comment by maximilianwulf** [comment]
Thank you. I think I don't have the rights to merge this one?

**Comment by wxmerkt** [comment]
I was waiting for CI to come back and went to a meeting - thanks for the ping. Do you require a new patch release to use these changes?

On another note, I'd like to merge #81 - could you please check if that would work with your use cases? (It shouldn't affect the functionality, but changes the API)

**Comment by maximilianwulf** [comment]
Thank you very much :) 

> Do you require a new patch release to use these changes?

I guess it will come naturally with the next release, right? If yes we are good for the moment. 

> could you please check if that would work with your use cases? (It shouldn't affect the functionality, but changes the API)

your PR changes `Eigen::Isometry3d TagDetector::getRelativeTransform`, right? We mainly use `AprilTagDetectionArray detectTags` as [interface](https://github.com/AprilRobotics/apriltag_ros/blob/10ba27c39d8d3907f197d136d5b2d2b1fde5e522/apriltag_ros/include/apriltag_ros/common_functions.h#L214). So from our side #81 should be fine.

**Pull request merged**
